name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up Node
       uses: actions/setup-node@v2
       with:
          node-version: '18.x'
     - name: Install dependencies

       run: npm install -g yarn

     - name: EC2 update
       env:
          EC2_HOST: ${{ secrets.HOST_IP }}
          EC2_USER: ${{ secrets.USER_NAME }}
          KEY_PATH: ${{ secrets.SSH_KEY }}
       run: |
           sudo apt-get update -y
           sudo apt-get install -y sshpass
           echo "${{ secrets.SSH_KEY }}" > key.pem
           chmod 600 key.pem

     - name: SSH and Deploy to EC2
       env:
         EC2_USER: ${{ secrets.USER_NAME }}
         EC2_HOST: ${{ secrets.HOST_IP }}
         KEY_PATH: ${{ secrets.SSH_KEY }}
       run: |
           ssh -i key.pem -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_IP} << 'EOF'
           cd /home/ubuntu/srv/Strapi_app/Strapi_let
           git pull
           yarn install
           yarn build
           pm2 start npm --name "Strapi" -- run start
           EOF
